### ISSUE TITLE
ob_get_contents get false issue

### ISSUE THREAD

**Issue by yayaigo2010** [VisualPHPUnit/VisualPHPUnit#133]
------- command line start
bin/vpu --xml_configuration_file app/config/phpunit.xml --snapshot_directory app/history -e -s

...(skip)
2) visualphpunit\StringCompareTest::oneThing
test_this() failed!
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'string'
+'different string'

/var/www/html/Temptation/Peter2/lib/VisualPHPUnit/app/test/StringCompareTest.php:39
/var/www/html/Temptation/Peter2/lib/VisualPHPUnit/app/lib/VPU.php:540

FAILURES!
Tests: 9, Assertions: 7, Errors: 1, Failures: 2, Skipped: 1, Incomplete: 1.
bool(false)
Snapshot successfully created at /var/www/html/Temptation/Peter2/lib/VisualPHPUnit/2015-08-20_12-01.html.
The statistics generated during this test run were successfully stored.
------- command line end

all the values are zero in 2015-08-20_12-01.html,
I trace the VPU.php code in runWithXml method below,
find out ob_get_contents() get "false",
but why always get false?

...(skip)
$results = ob_get_contents();
var_dump($results);//false
...(skip)

**Comment by localgod** [comment]
I think this issue is fixed in https://github.com/VisualPHPUnit/VisualPHPUnit/tree/%23130
Could you please try that branch.

**Comment by localgod** [comment]
I'm closing this one as no comments where provided by the poster for some time.
