### ISSUE TITLE
require autoload.php failled

### ISSUE THREAD

**Issue by noyessie** [VisualPHPUnit/VisualPHPUnit#145]
Please I just cloned the repo but i can't find the file autoload.php. I any don't have the vendor directory.?

**Comment by localgod** [comment]
VisualPHPUnit uses Composer to manage dependencies. You need to download and run `composer.phar update` in the root of the VisualPHPUnit folder.

you can get Composer her https://getcomposer.org/

**Comment by noyessie** [comment]
Thank you.
