### ISSUE TITLE
failed assert file

### ISSUE THREAD

**Issue by SilverioMiranda** [VisualPHPUnit/VisualPHPUnit#149]
In console : 

![image](https://cloud.githubusercontent.com/assets/1939153/11916517/f83ba1a4-a6c0-11e5-9ba2-cde1d536dec8.png)

```
 public function testLoadxml()
    {
        $file = "S:\33150716748567000180550010000015621058001101-nfe.xml";
        $this->assertFileExists($file);
}
```
This code dont work because bad scape sequence \\3

![image](https://cloud.githubusercontent.com/assets/1939153/11916520/29c21c4e-a6c1-11e5-9319-481b2eb6b605.png)

If i fix that the test works as expected :

![image](https://cloud.githubusercontent.com/assets/1939153/11916530/8d7d0ca8-a6c1-11e5-9734-60674a1a9482.png)

![image](https://cloud.githubusercontent.com/assets/1939153/11916535/bcfc0218-a6c1-11e5-89db-8acfba8b375d.png)

**Comment by localgod** [comment]
If you make a pull request with your fix I'll be happy to review it and add it to the [2.x branch](https://github.com/VisualPHPUnit/VisualPHPUnit/tree/2.x). I do not think this problem is present on the  [3.x branch](https://github.com/VisualPHPUnit/VisualPHPUnit/tree/3.x)

**Comment by localgod** [comment]
There will be no further development on the 2.x branch. Pull request that fixes this bug will merged.
