### ISSUE TITLE
Don't check for the phpunit test string to determine whether a file is a test

### ISSUE THREAD

**Issue by dawehner** [VisualPHPUnit/VisualPHPUnit#156]
Currently `https://github.com/VisualPHPUnit/VisualPHPUnit/blob/master/src/Api/Action/Test.php#L132` has a couple of issues:
- It doesn't support testbases, of which are there a lot of out there
- It doesn't execute the bootstrap, so potentially some classes cannot be loaded

**Comment by localgod** [comment]
As you are now able to specify the regxp for location test files in the configuration file for VPU you should be able to target any test file you like. Assuming the bootstrap file is located within the test folder in will be loaded automatically.
