### ISSUE TITLE
Not able to integrate with Laravel 5.2

### ISSUE THREAD

**Issue by kitrak17** [VisualPHPUnit/VisualPHPUnit#159]
Please release the version to integrate with laravel 5.2. It is not supporting currently.

**Comment by localgod** [comment]
What specifically prevents you from using it with laravel? VPU should work with any phpunit test.

**Comment by kitrak17** [comment]
It is not loading autoload.php file.

**Comment by localgod** [comment]
So I tried some stuff and actually got it working with the latest Laravel version. However:
Laravel extends the `PHPUnit_Framework_TestCase` class with its own `TestCase`. That is not a problem for VPU in itself. It dos however cause VPU to fail if the phpunit version used by VPU is substantial different from the one the test is written in.

At this time Laravel depends on ~4.0 of phpunit. VPU is currently depending on 5.3.4.
So what dos this mean for VPU and Laravel integration?

I will release a version that can detect Laravel test cases and list and execute them if the phpunit versions are compatible (if they are not vpu will ignore the test). I will not downgrade the phpunit dependency for VPU and I will not maintain a VPU version that supports phpunit 4.x

Once I have release the next version you can manually change the composer file for VPU to depend on a phpunit that matches Laravel. Then it _should_ work.

**Comment by kitrak17** [comment]
Thanks man :)

**Comment by localgod** [comment]
Please check out the #159 branch and remember to set phpunit to ~4.0 in composer.json for VPU.
If you are happy I will merge it in to the master branch an create a new release.

**Comment by kitrak17** [comment]
I did as you said above. But I am getting below error. Can you please check?

127.0.0.1:57580 [500]: /tests - require(): Failed opening required '/var/www/html/testmyblood/VisualPHPUnit/backend/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear:') in /var/www/html/testmyblood/VisualPHPUnit/backend/index.php on line 14

**Comment by kitrak17** [comment]
I created the file boostrap.php as like you said, now i could able to load the autoload.php file. But again I am facing problem . Below is the error I got.

127.0.0.1:33464 [500]: /tests - Class 'Visualphpunit\Api\Application\Vpu' not found in /var/www/html/testmyblood/VisualPHPUnit/backend/index.php on line 17

**Comment by localgod** [comment]
I'm hard press to debug anything without having access to a dump of you setup. 
It works for me with a clean install of the latest Laravel. I can run the the predefined test in the `tests` folder by adding a bootstrap with the lines specified in the previous comment, downgrading phpunit in `composer.json` and updating the `vpu.json` to include the Laravel tests folder.

Your error looks like a autoload error but I will need to review your code to help with your specific case.

**Comment by localgod** [comment]
Laravel 5.2 support was added to the master branch.
