### ISSUE TITLE
Visual-PHPunit testing on remote machine

### ISSUE THREAD

**Issue by bobc82** [VisualPHPUnit/VisualPHPUnit#160]
Is there a way to do phpunit (or visual-phpunit) testing on a remote (server) machine? (All that i would to do is to run remote test cases and view results in local browser...)

**Comment by sylfabre** [comment]
@bobc82 looks like you have to change `Gruntfile.js` at line 
@localgod Is it possible to run setup this using vpu.json file?

**Comment by localgod** [comment]
@sylfabre `vpu.json` only affects the backend at the moment. Another option could be to make in an option in the frontend to specify your backend in the gui.

**Comment by localgod** [comment]
Issue moved to #172.
