### ISSUE TITLE
Serialization of 'Closure' is not allowed - error when running tests

### ISSUE THREAD

**Issue by HeinDR** [VisualPHPUnit/VisualPHPUnit#164]
When I select a test and run it all tests result in the error ```Serialization of 'Closure' is not allowed```. After some research I discovered this was caused by PHPunit trying to serialise  the ```$GLOBALS```.
However in ```backend/index.php``` ```app``` is declared in the global scope. This adds the ```app``` to the ```$GLOBALS```. When PHPunit tries to serialise it it encounters a closure and throws this error. To solve this I changed ```backend/index.php```.  
```php
require __DIR__ . '/../vendor/autoload.php';
use Visualphpunit\Api\Application\Vpu;
<?php
/**
 * Prevent app to be added to the $GLOBALS
 *
 * @return void
 */
function run()
{
    $app = new Vpu();
    $app->run();
}

run();
```

**Comment by localgod** [comment]
Merged: 418eb41
