### ISSUE TITLE
VisualPHPUnit is not working with CakePHP 3

### ISSUE THREAD

**Issue by ankit-parikh** [VisualPHPUnit/VisualPHPUnit#181]
I want to integrate VisualPHPUnit with CakePHP 3.
I am able to install and execute VisualPHPUnit but i could not integrate it with CakePHP 3.
Please let me know how i can do this?
Thanks in advance.

**Comment by miguelxt** [comment]
+1

**Comment by localgod** [comment]
If Vpu fails to identify you test you might have to modifying this line in the config file:
https://github.com/VisualPHPUnit/VisualPHPUnit/blob/master/vpu.json#L8

**Comment by localgod** [comment]
Closing this one as there has been no follow up for some time.
