### ISSUE TITLE
Documentation Error?

### ISSUE THREAD

**Issue by CodeBlastr** [VisualPHPUnit/VisualPHPUnit#182]
Your wiki talks about a "public" folder (/app/public).  There is no public folder in the master branch of this repo.  From someone just getting started with your tool, it seems like the wiki was not written for the latest version, and I cannot get anything working.

**Comment by localgod** [comment]
You are correct. The wiki has not been updated to reflect the changes made in version 3. I will make sure this is more clear going forward. 
If you are running the latest and greatest from master the README.md file should be all you need.

**Comment by CodeBlastr** [comment]
I wish it were so, but it's running on a remote machine (not localhost).  I got something to show up in the browser by opening the /dist  (after running "grunt build"), but it is requesting http://localhost:8001/tests.  I don't see where to change that.  
![visualphpunit](https://cloud.githubusercontent.com/assets/393946/23755183/80e7b86c-04ad-11e7-9d34-98d863c061c2.png)

**Comment by localgod** [comment]
Have you tried modifying the config for the backend?
<img width="680" alt="screen shot 2017-03-12 at 19 41 46" src="https://cloud.githubusercontent.com/assets/1308965/23834759/046f19a4-075c-11e7-8275-8efa6a2e173a.png">

**Comment by localgod** [comment]
Closing this one as there has been no follow up for some time.
