### ISSUE TITLE
Does not work with Laravel 5.4

### ISSUE THREAD

**Issue by maxalmonte14** [VisualPHPUnit/VisualPHPUnit#186]
The tutorial provided in the wiki does not work with the latest version of Laravel because the folders and file structure are not the same to previous versions, the tutorial provided is not updated and I don't really know how to setup the package.

**Comment by Oxyde13** [comment]
I have same problem.

**Comment by localgod** [comment]
The tutorial in the wiki was written for the 2.x version. They will not work with the 3.x version. 
You should be able to get 3.x running with Laravel. It least I remember getting it working with 5.2.
Look here for hints: https://github.com/VisualPHPUnit/VisualPHPUnit/issues/159

I have updated the wiki to better reflect this fact.
